---
- name: Setup few variables
  set_fact:
    localhome: "/opt/fabric/{{ env }}/.composer"

- name: Make sure that working directory is clean
  become: true
  become_user: root
  file:
    path: "{{ localhome }}"
    state: "absent"
  with_items:
    - "absent"

- name: Check if composer playground container exist
  shell: docker ps -a|grep 'composer-playground'|cat|awk '{print $1}'
  register: pgc_state

- name: Stop composer playground
  command: docker rm -f composer-playground
  when: pgc_state.stdout != ""
  tags: "stopplayground"
